import Vue from 'vue'
import { Tab, Tabs, Checkbox, Dialog, ActionSheet, Icon, Search, Swipe, SwipeItem, Grid, GridItem, Toast, NavBar, Button, Switch, Rate, Tabbar, TabbarItem } from 'vant'

Vue.use(Tabs)
Vue.use(Tab)
Vue.use(Checkbox)
Vue.use(Dialog)
Vue.use(ActionSheet)
Vue.use(Icon)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Toast)
Vue.use(NavBar)
Vue.use(Button)
Vue.use(Switch)
Vue.use(Rate)
Vue.use(Tabbar)
Vue.use(TabbarItem)
